name: stack
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter: 
    sdk: flutter
  flutter_svg: ^1.0.3

dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  fonts:
    - family: Cairo
      fonts:
        - asset:  assets/fonts/Cairo/Cairo-Regular.ttf
        - asset:  assets/fonts/Cairo/Cairo-Black.ttf
        - asset:  assets/fonts/Cairo/Cairo-Bold.ttf
        - asset:  assets/fonts/Cairo/Cairo-SemiBold.ttf
  assets:
    - assets/images/undraw_pilates_gpdb.png
    - assets/icons/Excrecises.svg
    - assets/icons/yoga_women.svg
    - assets/icons/Meditation.svg
    - assets/icons/yoga.svg
    - assets/icons/Hamburger.svg
    - assets/icons/calendar.svg
    - assets/icons/gym.svg
    - assets/icons/Settings.svg


